### ISSUE TITLE
Duplicates returned  from am.get_project_chemistry

### ISSUE THREAD

**Issue by lisapro** [NIVANorge/Aquamonitor-Python#14]
This query return duplicates if I use Aqm-python 
```
pr_id = 12575
st_dt = "29.05.2023"
end_dt = "30.06.2023"

df = am.get_project_chemistry(pr_id, st_dt, end_dt, token=token)
df.loc[((df.station_code == 'BT124') & (df.depth1 == 17))]
```
While the same request directly to the database, returns unique values 
```
SELECT methods.name,value, depth1, depth2, projects.project_name, pr_st.station_name, pr_st.station_code as station, 
water_samples.sample_date, extract(year from sample_date) as "YEAR" ,pr_st.station_id, projects.project_id 
from nivadatabase.projects projects
join nivadatabase.projects_stations pr_st on pr_st.project_id  = projects.project_id 
join nivadatabase.water_samples water_samples on water_samples.station_id = pr_st.station_id 
join nivadatabase.water_chemistry_values water_chemistry on water_chemistry.water_sample_id = water_samples.water_sample_id 
join nivadatabase.method_definitions methods on methods.method_id = water_chemistry.method_id
where  projects.project_id =12575 and extract(year from sample_date) = 2023 and pr_st.station_code = 'BT124' and depth1 = 17
```
I tested it only for ØKOKYST Nordsjøen 2021-2025 (pr_id = 12575). And the duplicates were returned only for station 'BT124'  for all the depths between 17 and 25 m. 

Not sure what is the reason for this

**Comment by roarbra** [comment]
It seems like we had some duplicates in WCV_CALK.

There is some functionality in Nivadatabase to compute parameter values that are stored in WCV_CALK. Those are the values that are returned from AquaMonitor-Python. Unfortunately there are some hick up in those functions used to compute the values. In this situation there were some water_samples that were deleted.

If we can establish the history behind how those values were imported into the database, and what happened specifically for those depths that were duplicated, then we could look more into the details.

There are some procedures in the package pkg_wc_computed to update all values for a station or project.
