### ISSUE TITLE
pHT column in Aquamonitor has only pH_calc but not pH_sensor

### ISSUE THREAD

**Issue by lisapro** [NIVANorge/Aquamonitor-Python#17]
I queried Havforsuringsovervåkingen project for 2012 and when getting data directly from NIVADATABASE, I got a lot of pH values. They are registered with 2 different methods, pH_calc and pH_sensor. 

```SELECT methods.name,value, depth1, depth2, projects.project_name, pr_st.station_name, pr_st.station_code as station, water_samples.sample_date, extract(year from sample_date) as "YEAR" 
from nivadatabase.projects projects
join nivadatabase.projects_stations pr_st on pr_st.project_id  = projects.project_id 
join nivadatabase.water_samples water_samples on water_samples.station_id = pr_st.station_id 
join nivadatabase.water_chemistry_values water_chemistry on water_chemistry.water_sample_id = water_samples.water_sample_id 
join nivadatabase.method_definitions methods on methods.method_id = water_chemistry.method_id
where  projects.project_name in ('Havforsuringsovervåkingen') and methods.name like '%pH%' and extract(year from sample_date) = 2012
```

But when querying the same project, same range from Aquamonitor

```df = am.get_project_chemistry(10826, '01.01.2012', '31.12.2012', token=token)```

I got only two values for pH and these werer samples with pH_calc methond 

Is this a bug?

**Comment by roarbra** [comment]
No. It isn't a bug. There are a layer above water_chemistry_values / method_definitions that are used by AquaMonitor. This was done for harmonizing datasets with different units / names.
You can get the pH_sensor data out as pH in AquaMonitor by adding a row to wc_parameters_methods.

**Comment by lisapro** [comment]
where is this table and how to access it? 
So, do I understand correctly that data that can be accessed through Aquamonitor API and Aquamonit portal is a subset from nivadatabase defined somewhere? 

This data has been already reported to Vannmiljo. But then researchers will be able to see these data in Vannmiljo portal, but not in internal niva data viewers, unless they query nivadatabase directly. 

What is the logic/procedure for adding new parameters to Aquamonitor, how can I get overview of what else is different in Aqm and Nivadatabase?

**Comment by roarbra** [comment]
If you make an export in Aquamonitor, you will get all the data. Like in the attached file.
[Havforsuring 2012.xlsx](https://github.com/user-attachments/files/17111606/Havforsuring.2012.xlsx)
Raw data are in the sheet "Input water chemistry". Here you will recognize what you see with the query, while in "Water chemistry" the values are organised in what we call parameters. These numbers are taken from the table wcv_calk.

Instead of using sql to make those mappings. It's also possible to use [this](https://aquamonitor.niva.no/admin/methods.aspx) web form.
