### ISSUE TITLE
Method for biota chemistry would be nice

### ISSUE THREAD

**Issue by DagHjermann** [NIVANorge/Aquamonitor-Python#6]
Would be nice (for the wider NIVA community) to be able to extract biota chemistry, not only water chemistry. (Which then could also be included in the aquamoniR package for R as well.)

It's not really a problem for me personally, but it would enable more people to be able to handle data extraction/use. I've got a lot of R code for tables and figures that could be put into use..

**Comment by JamesSample** [comment]
Yep, I agree this would be very useful! 

Ultimately, it would be nice to be able to access all the data that is currently exported to Excel via the Aquamonitor web interface i.e. equivalents of the `WaterChemistry`, `SedimentChemistry` and `BiotaChemistry` worksheets, and maybe (but probably less importantly?) the `BunndyrVariables`, `BunndyrCounts` and `BegroingVariables` worksheets too.

At present, `query.map("water_chemistry_output")` in Aquamonitor-Python gives access to the same data as in the `WaterChemistry` worksheet. I think as far as Aquamonitor-Python is concerned, the only change should be doing e.g. `query.map("sediment_chemistry_output")` etc. instead. 

I'm not sure how much work is required on the backend to make this possible, though. What do you think, @roarbra?

**Comment by roarbra** [comment]
I've added some new end-points for biota chemistry:
_/api/projects/{projectId}/stations/{stationId}/biota/samples_
All samples at a station

_/api/projects/{projectId}/stations/{stationId}/biota/specimens_
All specimens at a station. The specimen is used as a name for the type of catch. That could either be a single fish, or a collection of blue mussels.

_/api/projects/{projectId}/stations/{stationId}/biota/samples/{sampleId}/values_
All chemistry values for a single sample. This is the raw data from the lab.

_/api/projects/{projectId}/stations/{stationId}/biota/samples/{sampleId}/specimens_
The specimens used for this specific sample. The same specimens can be joined to different samples.
