### ISSUE TITLE
Post cdom and ctd values from ODM2

### ISSUE THREAD

**Issue by lisapro** [NIVANorge/Aquamonitor-Python#8]
For the reporting purposes, it would be convenient to be able to post t the cdom values (calculated in cdom pipeline) to nivadatabase https://github.com/NIVANorge/nivacloud-cdom-ingestor 

To post a cdom sample values via Aquamanitor API, there are 2 api calls needed: 

1. User need to have “change” rights in Aquamonitor (need to be set up for each project)  
2. Post “water sample” with api/watersamples https://aquamonitor.niva.no/AquaServices/Help/Api/POST-api-watersamples
The response would give a sample  id back

3. Post values via water chemistry POST api/waterChemistry with sample id from the response 
https://aquamonitor.niva.no/AquaServices/Help/Api/POST-api-waterChemistry

 If something went wrong, it is possible to use PUT requests for updating data and DELETE requests for deleting wrong data 

4. Write python functions for aquamonitor module that would contain described above requests

**Comment by lisapro** [comment]
A couple of questions about aquamonitor API: @roarbra  
Should each value (for each depth)  of CTD have a unique water sample id? 

this is probably the function to call for post water sample ? 
```def postJson(token, path, inJson):
    response = requests.post(host + path, json=inJson, cookies=dict(aqua_key=token))
    if response.status_code == 200:
        return json.loads(response.text)
```
```
then here json would be the json from the example: 

{
  "Id": 1,
  "Depth1": 2.1,
  "Depth2": 3.1,
  "Method": {
    "Id": 1,
    "Code": "sample string 2",
    "Description": "sample string 3"
  },
  "SampleDate": "2023-03-20T11:21:13.5096303Z",
  "Station": {
    "Id": 1,
    "Project": {
      "Id": 1,
      "Name": "sample string 2",
      "Description": "sample string 3",
      "Number": "sample string 4",
      "StartDate": "2023-03-20T11:21:13.5096303Z",
      "EndDate": "2023-03-20T11:21:13.5096303Z"
    },
    "Type": {
      "Id": 1,
      "Text": "sample string 2"
    },
    "Code": "sample string 2",
    "Name": "sample string 3"
  },
  "Point": {
    "Id": 1,
    "Longitude": 1.1,
    "Latitude": 1.1,
    "EPSG": 2,
    "X": 3.1,
    "Y": 4.1
  },
  "Specifics": "sample string 5"
}
```

What are the required fields? This function is supposed to return sample id, then this is not required? 
If endpoint is api/watersamples, what would be the path for post request?

**Comment by roarbra** [comment]
> Should each value (for each depth) of CTD have a unique water sample id?
Yes. The unique key for water samples is: station_id, sample_date, depth1 and depth2.


> then here json would be the json from the example: 
> 
> {
>   "Id": 1,
>   "Depth1": 2.1,
>   "Depth2": 3.1,
>   "Method": {
>     "Id": 1,
>     "Code": "sample string 2",
>     "Description": "sample string 3"
>   },
>   "SampleDate": "2023-03-20T11:21:13.5096303Z",
>   "Station": {
>     "Id": 1,
>     "Project": {
>       "Id": 1,
>       "Name": "sample string 2",
>       "Description": "sample string 3",
>       "Number": "sample string 4",
>       "StartDate": "2023-03-20T11:21:13.5096303Z",
>       "EndDate": "2023-03-20T11:21:13.5096303Z"
>     },
>     "Type": {
>       "Id": 1,
>       "Text": "sample string 2"
>     },
>     "Code": "sample string 2",
>     "Name": "sample string 3"
>   },
>   "Point": {
>     "Id": 1,
>     "Longitude": 1.1,
>     "Latitude": 1.1,
>     "EPSG": 2,
>     "X": 3.1,
>     "Y": 4.1
>   },
>   "Specifics": "sample string 5"
> }
> ```
> 
> What are the required fields? This function is supposed to return sample id, then this is not required? If endpoint is api/watersamples, what would be the path for post request?

The full address would be:
https://test-aquamonitor.niva.no/AquaServices/api/watersamples

The json is quite simpler than in the documentation:
 {
   "Depth1": 2.1,
   "Depth2": 3.1,
   "SampleDate": "2023-03-20T11:21:13.5096303Z",
   "Station": {
     "Id": 1
   }
}

**Comment by lisapro** [comment]
ok, thank you! this is much simpler than in documentation
